### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by ibirone** [SiamKreative/Thanakarn-Icon-Font#1]
#### Divide Banks into categories
* Banks from Thailand
* Foreign Banks operating in Thailand

**Comment by siamkreative** [comment]
Thanks for the feedback 👍 

**I just added the name of Thai banks** (cb1d45000cb97cb07a0730daf5166a6a57f23074) but I don't think I will differentiate Thai Banks & Foreign Banks. I don't want to alter the [source file](https://github.com/omise/banks-logo/blob/master/banks.json).

Demo has been updated accordingly.
