### ISSUE TITLE
โหลดไม่ได้ครับ

### ISSUE THREAD

**Issue by chukiatt** [SiamKreative/Thanakarn-Icon-Font#6]
ลิงค์นี้เป็น Icon Font
https://labs.siamkreative.com/Thanakarn-Icon-Font/

ไม่ทราบว่าลิงค์นี้ใช้ไม่ได้แล้วเหรอครับ เสียดายมากเลยครับ

**Comment by siamkreative** [comment]
Lemme host it somewhere else :)

**Comment by siamkreative** [comment]
https://thanakarn-icon-font.netlify.app/
